{{- if .Values.autoGenerateSecrets.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vehicle-command.fullname" . }}-generate-secrets
  labels:
    {{- include "vehicle-command.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "vehicle-command.fullname" . }}-generate-secrets
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "vehicle-command.fullname" . }}-secret-generator
      initContainers:
      # Generate TLS certificates with OpenSSL
      - name: generate-tls
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          apk add --no-cache openssl
          echo "Generating TLS certificate and key..."
          openssl req -x509 -newkey rsa:2048 -nodes \
            -keyout /secrets/tls.key \
            -out /secrets/cert.pem \
            -days 365 \
            -subj "/CN={{ .Values.autoGenerateSecrets.tlsCN }}"
          echo "TLS certificates generated successfully"
        volumeMounts:
        - name: secrets
          mountPath: /secrets

      # Generate Tesla private/public key pair using OpenSSL
      - name: generate-tesla-key
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          apk add --no-cache openssl
          echo "Generating Tesla EC key pair (prime256v1)..."

          # Step 1: Generate private key using elliptic curve prime256v1
          openssl ecparam -name prime256v1 -genkey -noout -out /secrets/private.pem

          # Step 2: Generate public key from private key
          openssl ec -in /secrets/private.pem -pubout -out /secrets/public_key.pem

          echo "Tesla key pair generated successfully"
        volumeMounts:
        - name: secrets
          mountPath: /secrets

      containers:
      # Create Kubernetes secret using kubectl
      - name: create-secret
        image: alpine/k8s:1.28.13
        command:
        - /bin/sh
        - -c
        - |
          set -e

          # Check if secret already exists
          if kubectl get secret vehicle-command -n {{ .Release.Namespace }} 2>/dev/null; then
            echo "Secret 'vehicle-command' already exists, skipping creation"
            echo ""
            echo "To regenerate secrets, delete the existing resources first:"
            echo "kubectl delete secret vehicle-command -n {{ .Release.Namespace }}"
            echo "kubectl delete configmap vehicle-command-public-key -n {{ .Release.Namespace }}"
            exit 0
          fi

          echo "Creating Kubernetes secret 'vehicle-command'..."

          # Create the secret
          kubectl create secret generic vehicle-command \
            -n {{ .Release.Namespace }} \
            --from-file=tls.key=/secrets/tls.key \
            --from-file=cert.pem=/secrets/cert.pem \
            --from-file=private.pem=/secrets/private.pem

          echo "Secret 'vehicle-command' created successfully!"

          # Update ConfigMap with public key for web exposure
          kubectl create configmap vehicle-command-public-key \
            -n {{ .Release.Namespace }} \
            --from-file=com.tesla.3p.public-key.pem=/secrets/public_key.pem \
            --dry-run=client -o yaml | kubectl apply -f -

          echo "ConfigMap 'vehicle-command-public-key' updated successfully!"
          echo ""
          echo "=============================================================================="
          echo "  IMPORTANT: Tesla Fleet API Onboarding Required"
          echo "=============================================================================="
          echo ""
          echo "Your Tesla public key has been generated. You MUST register this key"
          echo "with Tesla Fleet API before you can use the vehicle-command service."
          echo ""
          echo "Steps to complete onboarding:"
          echo ""
          echo "1. Copy the public key below:"
          echo ""
          cat /secrets/public_key.pem
          echo ""
          echo "2. Visit the Tesla Developer Portal:"
          echo "   https://developer.tesla.com/"
          echo ""
          echo "3. Navigate to your application settings"
          echo ""
          echo "4. Add the public key above in the Fleet API configuration"
          echo ""
          echo "5. Wait for Tesla to approve your key (this may take some time)"
          echo ""
          echo "=============================================================================="
        volumeMounts:
        - name: secrets
          mountPath: /secrets

      volumes:
      - name: secrets
        emptyDir: {}
{{- end }}
