{{- if .Values.autoGenerateSecrets.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vehicle-command.fullname" . }}-secret-generator
  labels:
    {{- include "vehicle-command.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vehicle-command.fullname" . }}-secret-generator
  labels:
    {{- include "vehicle-command.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vehicle-command.fullname" . }}-secret-generator
  labels:
    {{- include "vehicle-command.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vehicle-command.fullname" . }}-secret-generator
subjects:
- kind: ServiceAccount
  name: {{ include "vehicle-command.fullname" . }}-secret-generator
  namespace: {{ .Release.Namespace }}
{{- end }}
