{{- range $secretName, $secretData := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "vehicle-command.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
